---
title: अन्तरिक्ष में खो गया
theme: green
hero_image: images/lost-in-space.png
description: अपनी स्वयं की एनिमेशन को प्रोग्राम करना सीखें!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
duration: 2
listed: false
copyedit: true
ingredient: false
interests: animation, space
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: भूमिका
- title: आपको किसकी ज़रूरत होगी
- title: स्पेसशिप एनिमेट करना
- title: लूप्स का इस्तेमाल करके एनिमेट करना
- title: तैरने वाला बंदर
- title: उछलने वाले क्षुद्रग्रह
- title: शाइनिंग स्टार
- title: 'चुनौती: अपनी स्वयं की एनिमेशन बनाना'

